// <auto-generated />
using EMPLOYE__DATA_API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMPLOYE__DATA_API.Migrations
{
    [DbContext(typeof(Empcls))]
    partial class EmpclsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMPLOYE__DATA_API.Model.Emp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("emp_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("emp_post")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("emp_sal")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("emps");
                });
#pragma warning restore 612, 618
        }
    }
}
